import pandas as pd
import os

def load_data(filename):
    """Loads raw data from the data directory."""
    # Robust path handling
    script_dir = os.path.dirname(os.path.abspath(__file__))
    project_root = os.path.dirname(script_dir)
    file_path = os.path.join(project_root, "data", filename)
    
    df = pd.read_csv(file_path)
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values('date')
    return df, project_root

def calculate_rsi(series, period=14):
    """Calculates Relative Strength Index (RSI)."""
    delta = series.diff()
    gain = (delta.where(delta > 0, 0)).rolling(window=period).mean()
    loss = (-delta.where(delta < 0, 0)).rolling(window=period).mean()
    
    rs = gain / loss
    return 100 - (100 / (1 + rs))

def add_features(df):
    """Adds technical indicators and lag features."""
    df = df.copy()
    
    # 1. Moving Averages (Trend)
    df['sma_7'] = df['price'].rolling(window=7).mean()
    df['sma_30'] = df['price'].rolling(window=30).mean()
    
    # 2. RSI (Momentum)
    df['rsi'] = calculate_rsi(df['price'])
    
    # 3. Lag Features (Past context for the model)
    # The model will use yesterday's price to predict today's
    df['price_lag_1'] = df['price'].shift(1)
    df['price_lag_7'] = df['price'].shift(7)
    
    # 4. Volatility (Standard Deviation)
    df['volatility'] = df['price'].rolling(window=7).std()
    
    # Drop NaN values generated by rolling/shifting (first 30 days will be empty)
    df.dropna(inplace=True)
    
    return df

def main():
    try:
        print("1. Loading raw data...")
        df, project_root = load_data("bitcoin_prices.csv")
        
        print("2. Adding technical features...")
        df_processed = add_features(df)
        
        print(f"Features added. New shape: {df_processed.shape}")
        print(df_processed.tail())
        
        # Save processed data
        output_path = os.path.join(project_root, "data", "bitcoin_processed.csv")
        df_processed.to_csv(output_path, index=False)
        print(f"Success! Processed data saved at: {output_path}")
        
    except FileNotFoundError:
        print("Error: 'bitcoin_prices.csv' not found. Run fetch_data.py first.")
    except Exception as e:
        print(f"Unexpected error: {e}")

if __name__ == "__main__":
    main()